version: '3.9'

services:
  vuejs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: >
      sh -c "npm install && npm run dev"

volumes:
  node_modules:
